### PR TITLE
spelling correction

### PR DESCRIPTION
**Pull request by habi3000**
Thanks a lot for your help.

### CODE REVIEW

**Comment by kriswiner** [comment]
One other thing Mohamed, I don;t want to replace the existing sketches with
your work, can you simply put your stuff in a folder and then I will add
the folder to the repository. Thank you.

**Comment by habi3000** [comment]
ok, that is also good it will provide users with more options. what should  i call that folder??

**Comment by kriswiner** [comment]
How about MPU6050Library? You can do a pull request or just send me the
folder and I will drop it into the repository.

**Comment by habi3000** [comment]
is this good enough ?

**Comment by kriswiner** [comment]
Yes, thank you.

**Comment by habi3000** [comment]
happy to help.

**Pull request merged**
